### ISSUE TITLE
Navigation Tree (Fellow Stories)

### ISSUE THREAD

**Issue by gichiba** [ethereum/nxbn-website#131]
**Describe the bug**

When navigating with the chapters/headings map on the right hand side of a fellow story, when clicking the file path includes the last-clicked heading. 

E.G. -- clicking on 'upgrading bureaucracy' for Chuy's story then shows

`fellowship / Chuy#the-long-view` at the top

![Screen_Shot_2024-05-23_11_44_41_AM](https://github.com/ethereum/nxbn-website/assets/9886144/5b989176-ade7-4d7b-9b34-7bed8cabb284)

**Comment by corwintines** [comment]
Note to self: Strip out headings from breadcrumbs
