### ISSUE TITLE
Globe too big on some mobile views

### ISSUE THREAD

**Issue by gichiba** [ethereum/nxbn-website#133]
As it says on the tin; for screen sizes around ~376 px -- the globe is a little too big and wide. 

Also there is a very small misalignment whereby the right hand side of the site clips a little bit and you see the background color instead of the textured night sky or whatever. 

![Screen_Shot_2024-05-23_12_01_13_AM](https://github.com/ethereum/nxbn-website/assets/9886144/1d6d99c3-c433-4651-9f48-f649844b3d71)

**Comment by gichiba** [comment]
![Screenshot from 2024-06-07 12-19-00](https://github.com/ethereum/nxbn-website/assets/9886144/d9e7b71c-f972-4cee-bef5-c7f9c322f70c)


Additionally, the location marker is positioned too far north for screen widths less than 768px

**Comment by corwintines** [comment]
I think I have addressed this now if you dont mind testing @gichiba!
