### ISSUE TITLE
Fix globe responsiveness

### ISSUE THREAD

**Issue by corwintines** [ethereum/nxbn-website#95]
On smaller screens the responsiveness of the Globe component on the homepage hero needs improvement.

**Comment by gichiba** [comment]
I don't know if this is related to the responsiveness, specifically, but I'm getting a double-globe: 

![Screenshot from 2024-04-16 12-17-24](https://github.com/ethereum/fellowship-program-website/assets/9886144/a9e29f89-a6a4-4fe1-980f-6ad15e5d82ff)

**Comment by minimalsm** [comment]
two globe problem

**Comment by corwintines** [comment]
@gichiba ill try and figure out what is going on here. What is interesting is that this isn't in the production build 🤔

**Comment by corwintines** [comment]
Just pushed up a fix for the two globe problem
